spring:
  # project
  application:
    name: KuraBlog-Backend

  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kurablog
    username: root
    password: 123456

# mybatis
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# aliyun
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucketName: kurablog
    region: cn-hangzhou

# jwt
jwt:
  secret: usingaskurablogtemplatejwtsecretkey
  access-token-expire: 30 # min
  refresh-token-expire: 168 # hour